services:
    david63.friendsandfoes.admin.controller:
        class: david63\friendsandfoes\controller\admin_controller
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @pagination
